using CommandLine;

namespace KSeFCli;

[Verb("XML2PDF", HelpText = "Convert KSeF XML invoice to PDF.")]
public class XML2PDFCommand : IGlobalCommand
{
    [Value(0, Required = true, HelpText = "Input XML file path.")]
    public required string InputFile { get; set; }

    [Value(1, HelpText = "Output PDF file path.")]
    public string? OutputFile { get; set; }

    public override async Task<int> ExecuteAsync(CancellationToken cancellationToken)
    {
        ConfigureLogging();

        if (!File.Exists(InputFile))
        {
            Console.Error.WriteLine($"Error: Input file not found: {InputFile}");
            return 1;
        }

        string outputPdfPath;
        if (string.IsNullOrEmpty(OutputFile))
        {
            if (!InputFile.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
            {
                Console.Error.WriteLine("Error: Input file must have a .xml extension when no output file is specified.");
                return 1;
            }
            outputPdfPath = Path.ChangeExtension(InputFile, ".pdf");
            if (File.Exists(outputPdfPath))
            {
                Console.Error.WriteLine($"Error: Output file already exists: {outputPdfPath}");
                return 1;
            }
        }
        else
        {
            outputPdfPath = OutputFile;
        }

        string xmlContent = await File.ReadAllTextAsync(InputFile, cancellationToken).ConfigureAwait(false);
        byte[] pdfContent = await XML2PDF(xmlContent, Quiet, cancellationToken).ConfigureAwait(false);

        await File.WriteAllBytesAsync(outputPdfPath, pdfContent, cancellationToken).ConfigureAwait(false);

        Console.WriteLine($"PDF saved to: {outputPdfPath}");

        return 0;
    }

    private static string[] GetPdfCommand(string inputXml, string outputPdf)
    {
        // 1. Check for bundled SEA binary alongside ksefcli
        string ext = OperatingSystem.IsWindows() ? ".exe" : "";
        string bundledPath = Path.Combine(AppContext.BaseDirectory, $"ksef-pdf-generator{ext}");
        if (File.Exists(bundledPath))
        {
            return [bundledPath, "invoice", inputXml, outputPdf];
        }

        // 2. Check for ksef-pdf-generator in PATH
        if (Subprocess.CheckCommandExists("ksef-pdf-generator"))
        {
            return ["ksef-pdf-generator", "invoice", inputXml, outputPdf];
        }

        // 3. Fallback to npx (requires git to be installed)
        if (!Subprocess.CheckCommandExists("npx"))
        {
            throw new InvalidOperationException(
                "ksef-pdf-generator not found. Either place it alongside ksefcli, install Node.js (npx), or disable PDF export.");
        }

        return ["npx", "--yes", "github:kamilcuk/ksef-pdf-generator", "invoice", inputXml, outputPdf];
    }

    /// <summary>
    /// Returns the path to a Node.js polyfill file that defines <c>global.navigator</c>
    /// if it does not already exist. This fixes "navigator is not defined" crashes in
    /// pdfmake's browser-compiled bundle when running under newer Node.js versions that
    /// partially expose <c>navigator</c> as a global but lack <c>navigator.userAgent</c>.
    /// </summary>
    private static string EnsureNodePolyfill()
    {
        string cacheDir = Path.Combine(
            System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile),
            ".cache", "ksefcli");
        Directory.CreateDirectory(cacheDir);

        string polyfillPath = Path.Combine(cacheDir, "node-browser-polyfill.js");
        if (!File.Exists(polyfillPath))
        {
            File.WriteAllText(polyfillPath,
                "// Auto-generated by ksefcli — polyfills browser globals missing in Node.js\n" +
                "if (typeof navigator === 'undefined' || typeof navigator.userAgent === 'undefined') {\n" +
                "  Object.defineProperty(global, 'navigator', {\n" +
                "    value: { userAgent: 'Node.js', platform: process.platform },\n" +
                "    writable: true, configurable: true\n" +
                "  });\n" +
                "}\n" +
                "if (typeof window === 'undefined') {\n" +
                "  global.window = global;\n" +
                "}\n");
        }
        return polyfillPath;
    }

    public static async Task<byte[]> XML2PDF(string xmlContent, bool quiet, CancellationToken cancellationToken)
    {
        using TemporaryFile tempXml = new(extension: ".xml");
        await File.WriteAllTextAsync(tempXml.Path, xmlContent, cancellationToken).ConfigureAwait(false);
        using TemporaryFile tempPdf = new(extension: ".pdf");

        string[] cmd = GetPdfCommand(tempXml.Path, tempPdf.Path);

        Dictionary<string, string?>? env = null;
        if (cmd[0] == "npx" || cmd[0] == "ksef-pdf-generator")
        {
            // Inject a navigator polyfill via NODE_OPTIONS --require so pdfmake's browser-compiled
            // bundle doesn't crash with "navigator is not defined" on Node.js 20+
            string polyfillPath = EnsureNodePolyfill();
            string existing = System.Environment.GetEnvironmentVariable("NODE_OPTIONS") ?? "";
            string requireFlag = $"--require {polyfillPath}";
            env = new Dictionary<string, string?>
            {
                ["NODE_OPTIONS"] = string.IsNullOrEmpty(existing)
                    ? requireFlag
                    : $"{existing} {requireFlag}",
            };
        }

        Subprocess proc = new(CommandAndArgs: cmd, Environment: env, Quiet: quiet);
        await proc.CheckCallAsync(cancellationToken).ConfigureAwait(false);
        return await File.ReadAllBytesAsync(tempPdf.Path, cancellationToken).ConfigureAwait(false);
    }

    public static void AssertPdfGeneratorAvailable()
    {
        string ext = OperatingSystem.IsWindows() ? ".exe" : "";
        string bundledPath = Path.Combine(AppContext.BaseDirectory, $"ksef-pdf-generator{ext}");
        if (File.Exists(bundledPath))
        {
            return;
        }

        if (Subprocess.CheckCommandExists("ksef-pdf-generator"))
        {
            return;
        }

        if (Subprocess.CheckCommandExists("npx"))
        {
            return;
        }

        throw new InvalidOperationException(
            "PDF generation requires ksef-pdf-generator binary or Node.js (npx). Neither found.");
    }
}
